name: Check ESLint and Types

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.7.0'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          npx yarn --ci --prefer-offline
          npx yarn bootstrap
      - name: Build For Dev
        run: |
          npx yarn build-dev
      - name: Run ESLint
        run: |
          npm run eslint
      - name: Run Type Check
        run: |
          npm run type-check
