name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.7.0"
      - name: Install Dependencies
        run: |
          npx yarn --ci
      - name: Run ESLint
        run: |
          npm run eslint
