name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  check:
    uses: ./.github/workflows/check.yml
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.7.0'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          npx yarn --ci --prefer-offline
          npx yarn bootstrap
      - name: Build
        run: |
          npm run build
