name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.7.0'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          npx yarn --ci --prefer-offline
      - name: Run ESLint
        run: |
          npm run eslint
