name: "Tag Release"

on:
  push:
    tags:
      - "v*"

jobs:
  call-workflow-check:
    uses: ./.github/workflows/check.yml
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.7.0'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          npx yarn --ci --prefer-offline
      - name: Build
        run: |
          npm run build
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:always-auth=true
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.tgz
